### ISSUE TITLE
PEP725 specificEpithet names have a preceeding space

### ISSUE THREAD

**Issue by jdeck88** [jdeck88/pheno_paper#26]
e.g. " rober"
need to remove space in pre-processing step

**Comment by rodney757** [comment]
It looks like there is 2 pep725 process.py scripts. 1 in bin/preProcessors and the other in bin/projects.

this is fixed in bin/projects/pep725/process.py script.

**Comment by jdeck88** [comment]
ok, i removed the bin/preProcessors directory-- that shouldn't be there.
thanks
